# config/example.param.yaml
---

ndt_map_publisher_node:
  ros__parameters:
    map_topic: "ndt_map"
    map_file_name: "/home/yunus.caliskan/data/AutonomouStuff.pcd"
    map_frame: "map"
    num_expected_subs: 1
    init_timeout_ms: 10000  # 10 seconds until publisher finds a subscriber
    map_config:
      capacity: 550000
      min_point:
        x: -850.0
        y: -850.0
        z: -3.0
      max_point:
        x: 850.0
        y: 850.0
        z: 3.0
      voxel_size:
        x: 3.5
        y: 3.5
        z: 3.5