# param/p2d_ndt_node.param.yaml
---

p2d_ndt_localizer_node:
  ros__parameters:
    ##### Define input and outputs:
    observation_sub:  # Config of the input point cloud subscription
      topic: "points_downsampled"
      history_depth: 30
    # Config of the maps point cloud subscription
    map_sub:
      topic: "ndt_map"
      history_depth: 10
    # Config of the maps point clouds to register
    pose_pub:
      topic: "ndt_pose"
      history_depth: 10
    # localizer specific configuration
    localizer:
      #underlying voxel grid configuration of the map
      map:
        capacity: 550000
        min_point:
          x: -850.0
          y: -850.0
          z: -3.0
        max_point:
          x: 850.0
          y: 850.0
          z: 3.0
        voxel_size:
          x: 3.5
          y: 3.5
          z: 3.5
      # ndt scan representation config
      scan:
        capacity: 55000
      # ndt optimization problem configuration
      optimization:
        outlier_ratio: 0.45 # default value from PCL
      # newton optimizer configuration
      optimizer:
        max_iterations: 30
        score_tolerance: 0.0002
        parameter_tolerance: 0.0002
        gradient_tolerance: 0.05
        line_search:
          step_size: 0.12
      # Maximum accepted duration between a scan and an initial pose guess
      guess_time_tolerance_ms: 650