# param/p2d_ndt_node.param.yaml
---

p2d_ndt_localizer_node:
  ros__parameters:
    ##### Define input and outputs:
    observation_sub:  # Config of the input point cloud subscription
      topic: "points_raw"
      history_depth: 20
    # Config of the maps point cloud subscription
    map_sub:
      topic: "ndt_map"
      history_depth: 10
    # Config of the maps point clouds to register
    pose_pub:
      topic: "ndt_pose"
      history_depth: 10
    # localizer specific configuration
    localizer:
      #underlying voxel grid configuration of the map
      map:
        capacity: 550000
        min_point:
          x: -1850.0
          y: -1850.0
          z: -3.0
        max_point:
          x: 1850.0
          y: 1850.0
          z: 3.0
        voxel_size:
          x: 1.0
          y: 1.0
          z: 1.0
      # ndt scan representation config
      scan:
        capacity: 55000
      # ndt optimization problem configuration
      optimization:
        outlier_ratio: 0.55 # default value from PCL
      # newton optimizer configuration
      optimizer:
        max_iterations: 50
        score_tolerance: 0.001
        parameter_tolerance: 0.0001
        gradient_tolerance: 0.0005
        line_search:
          step_size: 0.01
      # Maximum accepted duration between a scan and an initial pose guess
      guess_time_tolerance_ms: 2000